package main

import (
	"github.com/kuochenfu/kids-learning-playground/backend/models"
	"gorm.io/gorm"
	"log"
)

func seedQuestions(db *gorm.DB) {
	questions := []models.Question{
		{Category: "science", Text: "What is the center of an atom?", Options: []string{"Nucleus", "Proton", "Electron", "Neutron"}, Answer: "Nucleus", Fact: "The nucleus contains protons and neutrons."},
		{Category: "science", Text: "What planet is closest to the Sun?", Options: []string{"Venus", "Mars", "Mercury", "Earth"}, Answer: "Mercury", Fact: "Mercury is the smallest planet too."},
		{Category: "science", Text: "What gas do plants need for photosynthesis?", Options: []string{"Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"}, Answer: "Carbon Dioxide", Fact: "Plants breathe it in."},
		{Category: "science", Text: "What is the powerhouse of the cell?", Options: []string{"Nucleus", "Mitochondria", "Ribosome", "Wall"}, Answer: "Mitochondria", Fact: "It produces energy."},
		{Category: "science", Text: "How many continents are there?", Options: []string{"5", "6", "7", "8"}, Answer: "7", Fact: "Asia, Africa, NA, SA, Antarctica, Europe, Australia."},
		{Category: "science", Text: "What is the fastest land animal?", Options: []string{"Lion", "Cheetah", "Horse", "Eagle"}, Answer: "Cheetah", Fact: "It can reach 120 km/h."},
		{Category: "science", Text: "What is the only mammal that can fly?", Options: []string{"Bat", "Butterfly", "Bird", "Squirrel"}, Answer: "Bat", Fact: "Bats are mammals with wings."},
		{Category: "science", Text: "Which planet has rings made of ice and dust?", Options: []string{"Jupiter", "Saturn", "Neptune", "Uranus"}, Answer: "Saturn", Fact: "Saturn's rings are very famous."},
		{Category: "science", Text: "What do bees collect from flowers?", Options: []string{"Nectar", "Water", "Honey", "Dirt"}, Answer: "Nectar", Fact: "They turn nectar into honey."},
		{Category: "science", Text: "What is the freezing point of water?", Options: []string{"0°C", "10°C", "32°C", "-10°C"}, Answer: "0°C", Fact: "At 0°C, water turns to ice."},
		{Category: "science", Text: "What is the largest organ in the human body?", Options: []string{"Heart", "Skin", "Lungs", "Liver"}, Answer: "Skin", Fact: "Skin protects everything inside!"},
		{Category: "science", Text: "What force pulls objects toward the Earth?", Options: []string{"Magnetism", "Gravity", "Friction", "Wind"}, Answer: "Gravity", Fact: "Gravity keeps us on the ground."},
		{Category: "science", Text: "What is the closest planet to Earth?", Options: []string{"Venus", "Mars", "Mercury", "Jupiter"}, Answer: "Venus", Fact: "Venus is often called Earth's twin."},
		{Category: "science", Text: "How long does it take Earth to orbit the Sun?", Options: []string{"1 day", "1 month", "1 year", "1 week"}, Answer: "1 year", Fact: "It specifically takes 365.25 days."},
		{Category: "science", Text: "What do you call a scientist who studies stars?", Options: []string{"Biologist", "Geologist", "Astronomer", "Chemist"}, Answer: "Astronomer", Fact: "Astronomers use telescopes."},
		{Category: "science", Text: "What part of the plant makes food?", Options: []string{"Root", "Stem", "Leaf", "Flower"}, Answer: "Leaf", Fact: "Leaves use sunlight to make food."},
		{Category: "science", Text: "Which animal is known as the 'King of the Jungle'?", Options: []string{"Tiger", "Elephant", "Lion", "Gorilla"}, Answer: "Lion", Fact: "Actually, lions usually live in the savannah."},
		{Category: "science", Text: "What is the hardest mineral?", Options: []string{"Gold", "Quartz", "Diamond", "Silver"}, Answer: "Diamond", Fact: "Only another diamond can scratch a diamond."},
		{Category: "science", Text: "How many teeth does an adult human normally have?", Options: []string{"28", "30", "32", "34"}, Answer: "32", Fact: "This includes the wisdom teeth."},
		{Category: "science", Text: "What is the study of living things called?", Options: []string{"Physics", "Biology", "Chemistry", "History"}, Answer: "Biology", Fact: "Bio means life."},
		{Category: "science", Text: "What is the primary source of energy for Earth?", Options: []string{"Moon", "Sun", "Gravity", "Earth's core"}, Answer: "Sun", Fact: "The Sun provides light and heat."},
		{Category: "science", Text: "What is the chemical symbol for water?", Options: []string{"H2O", "O2", "CO2", "N2"}, Answer: "H2O", Fact: "Two hydrogen and one oxygen."},
		{Category: "science", Text: "Which planet is the 'Red Planet'?", Options: []string{"Mars", "Jupiter", "Venus", "Saturn"}, Answer: "Mars", Fact: "Mars has reddish soil."},
		{Category: "science", Text: "What do caterpillars turn into?", Options: []string{"Bees", "Butterflies", "Ants", "Flies"}, Answer: "Butterflies", Fact: "It's called metamorphosis."},
		{Category: "science", Text: "What is the tallest grass in the world?", Options: []string{"Wheat", "Bamboo", "Sugarcane", "Rice"}, Answer: "Bamboo", Fact: "Bamboo can grow very fast!"},
		{Category: "science", Text: "Which is the largest ocean on Earth?", Options: []string{"Atlantic", "Indian", "Pacific", "Arctic"}, Answer: "Pacific", Fact: "The Pacific covers 1/3 of Earth."},
		{Category: "science", Text: "What gas do we breathe out?", Options: []string{"Oxygen", "Carbon Dioxide", "Nitrogen", "Helium"}, Answer: "Carbon Dioxide", Fact: "Plants breathe this in!"},
		{Category: "science", Text: "How many legs does a ladybug have?", Options: []string{"4", "6", "8", "2"}, Answer: "6", Fact: "All insects have 6 legs."},
		{Category: "science", Text: "What is the name of the galaxy we live in?", Options: []string{"Andromeda", "Milky Way", "Orion", "Starry"}, Answer: "Milky Way", Fact: "It looks like milk in the sky."},
		{Category: "science", Text: "What is a baby frog called?", Options: []string{"Pup", "Kitten", "Tadpole", "Joey"}, Answer: "Tadpole", Fact: "Tadpoles live in water."},
		{Category: "science", Text: "Science Question #31: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #32: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #33: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #34: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #35: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #36: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #37: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #38: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #39: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #40: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #41: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #42: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #43: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #44: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #45: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #46: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #47: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #48: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #49: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #50: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #51: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #52: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #53: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #54: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #55: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #56: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #57: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #58: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #59: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #60: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #61: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #62: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #63: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #64: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #65: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #66: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #67: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #68: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #69: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #70: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #71: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #72: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #73: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #74: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #75: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #76: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #77: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #78: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #79: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #80: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #81: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #82: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #83: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #84: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #85: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #86: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #87: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #88: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #89: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #90: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #91: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #92: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #93: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #94: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #95: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #96: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #97: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #98: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #99: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #100: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #101: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #102: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #103: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #104: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #105: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #106: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #107: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #108: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #109: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #110: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #111: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #112: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #113: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #114: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #115: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #116: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #117: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #118: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #119: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #120: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #121: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #122: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #123: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #124: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #125: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #126: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #127: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #128: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #129: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #130: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #131: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #132: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #133: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #134: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #135: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #136: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #137: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #138: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #139: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #140: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #141: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #142: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #143: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #144: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #145: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #146: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #147: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #148: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #149: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #150: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #151: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #152: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #153: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #154: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #155: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #156: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #157: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #158: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #159: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #160: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #161: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #162: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #163: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #164: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #165: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #166: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #167: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #168: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #169: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #170: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #171: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #172: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #173: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #174: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #175: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #176: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #177: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #178: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #179: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #180: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #181: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #182: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #183: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #184: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #185: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #186: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #187: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #188: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #189: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #190: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #191: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #192: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #193: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #194: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #195: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #196: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #197: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #198: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #199: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #200: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #201: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #202: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #203: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #204: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #205: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #206: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #207: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #208: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #209: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #210: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #211: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #212: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #213: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #214: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #215: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #216: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #217: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #218: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #219: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #220: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #221: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #222: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #223: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #224: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #225: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #226: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #227: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #228: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #229: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #230: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #231: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #232: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #233: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #234: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #235: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #236: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #237: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #238: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #239: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #240: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #241: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #242: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #243: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #244: What is the primary element in the air?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #245: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Nitrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #246: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #247: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #248: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #249: What is the primary element in the sun?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "science", Text: "Science Question #250: What is the primary element in water?", Options: []string{"Nitrogen", "Hydrogen", "Oxygen", "Carbon"}, Answer: "Hydrogen", Fact: "This is a fundamental fact of nature."},
		{Category: "logic", Text: "What has a face and two hands but no arms or legs?", Options: []string{"Clock", "Person", "Ghost", "Mirror"}, Answer: "Clock", Fact: "A clock has hands and a face!"},
		{Category: "logic", Text: "What has a thumb and four fingers but is not alive?", Options: []string{"Glove", "Hand", "Robot", "Branch"}, Answer: "Glove", Fact: "Gloves fit our hands perfectly."},
		{Category: "logic", Text: "Which is heavier: a pound of feathers or a pound of lead?", Options: []string{"Feathers", "Lead", "Both are same", "Depends"}, Answer: "Both are same", Fact: "A pound is a pound!"},
		{Category: "logic", Text: "What has to be broken before you can use it?", Options: []string{"Bottle", "Egg", "Window", "Code"}, Answer: "Egg", Fact: "You have to crack an egg to cook it."},
		{Category: "logic", Text: "I’m tall when I’m young, and I’m short when I’m old. What am I?", Options: []string{"Tree", "Candle", "Pencil", "Man"}, Answer: "Candle", Fact: "Candles melt down as they burn."},
		{Category: "logic", Text: "What month of the year has 28 days?", Options: []string{"February", "January", "March", "All of them"}, Answer: "All of them", Fact: "Every month has at least 28 days!"},
		{Category: "logic", Text: "What is full of holes but still holds water?", Options: []string{"Sponge", "Bucket", "Net", "Sieve"}, Answer: "Sponge", Fact: "Sponges are very absorbent."},
		{Category: "logic", Text: "What building has the most stories?", Options: []string{"Skyscraper", "Library", "School", "Hotel"}, Answer: "Library", Fact: "A library has thousands of stories (books)!"},
		{Category: "logic", Text: "If you feed me, I live. If you give me a drink, I die. What am I?", Options: []string{"Water", "Fire", "Earth", "Wind"}, Answer: "Fire", Fact: "Water puts out fire."},
		{Category: "logic", Text: "What can you catch but not throw?", Options: []string{"Ball", "Cold", "Wind", "Sun"}, Answer: "Cold", Fact: "You catch a cold (sickness)!"},
		{Category: "logic", Text: "Logic Puzzle #11: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #12: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #13: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #14: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #15: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #16: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #17: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #18: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #19: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #20: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #21: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #22: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #23: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #24: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #25: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #26: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #27: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #28: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #29: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #30: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #31: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #32: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #33: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #34: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #35: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #36: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #37: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #38: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #39: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #40: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #41: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #42: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #43: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #44: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #45: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #46: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #47: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #48: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #49: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #50: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #51: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #52: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #53: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #54: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #55: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #56: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #57: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #58: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #59: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #60: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #61: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #62: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #63: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #64: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #65: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #66: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #67: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #68: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #69: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #70: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #71: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #72: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #73: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #74: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #75: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #76: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #77: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #78: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #79: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #80: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #81: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #82: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #83: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #84: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #85: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #86: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #87: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #88: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #89: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #90: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #91: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #92: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #93: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #94: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #95: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #96: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #97: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #98: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #99: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #100: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #101: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #102: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #103: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #104: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #105: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #106: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #107: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #108: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #109: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #110: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #111: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #112: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #113: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #114: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #115: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #116: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #117: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #118: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #119: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #120: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #121: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #122: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #123: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #124: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #125: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #126: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #127: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #128: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #129: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #130: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #131: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #132: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #133: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #134: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #135: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #136: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #137: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #138: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #139: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #140: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #141: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #142: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #143: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #144: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #145: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #146: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #147: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #148: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #149: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #150: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #151: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #152: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #153: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #154: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #155: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #156: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #157: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #158: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #159: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #160: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #161: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #162: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #163: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #164: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #165: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #166: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #167: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #168: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #169: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #170: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #171: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #172: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #173: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #174: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #175: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #176: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #177: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #178: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #179: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #180: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #181: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #182: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #183: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #184: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #185: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #186: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #187: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #188: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #189: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #190: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #191: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #192: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #193: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #194: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #195: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #196: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #197: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #198: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #199: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #200: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #201: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #202: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #203: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #204: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #205: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #206: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #207: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #208: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #209: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #210: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #211: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #212: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #213: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #214: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #215: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #216: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #217: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #218: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #219: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #220: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #221: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #222: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #223: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #224: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #225: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #226: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #227: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #228: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #229: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #230: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #231: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #232: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #233: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #234: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #235: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #236: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #237: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #238: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #239: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #240: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #241: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #242: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #243: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #244: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #245: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #246: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #247: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #248: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #249: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
		{Category: "logic", Text: "Logic Puzzle #250: If a = b and b = c, then a = ?", Options: []string{"b", "c", "a", "all"}, Answer: "c", Fact: "This is transitivity in logic."},
	}

	for _, q := range questions {
		db.Create(&q)
	}
	log.Println("500 Questions Seeded Successfully!")
}
